export type AuditAction =
    | 'APP_CREATED'
    | 'APP_UPDATED'
    | 'APP_KILLED'
    | 'APP_REVIVED'
    | 'CAMPAIGN_CREATED'
    | 'CAMPAIGN_UPDATED'
    | 'CAMPAIGN_SCHEDULED'
    | 'CAMPAIGN_SENT'
    | 'CAMPAIGN_CANCELLED'
    | 'CAMPAIGN_DELETED'
    | 'CAMPAIGN_DUPLICATED'
    | 'ABTEST_CREATED'
    | 'ABTEST_UPDATED'
    | 'ABTEST_STARTED'
    | 'ABTEST_CANCELLED'
    | 'ABTEST_DELETED'
    | 'ABTEST_DUPLICATED'
    | 'TEMPLATE_CREATED'
    | 'TEMPLATE_UPDATED'
    | 'TEMPLATE_DELETED'
    | 'NOTIFICATION_CREATED'
    | 'NOTIFICATION_SCHEDULED'
    | 'NOTIFICATION_CANCELLED'
    | 'NOTIFICATION_FORCE_SENT'
    | 'NOTIFICATION_TEST_SENT'
    | 'CREDENTIAL_SET'
    | 'CREDENTIAL_DELETED'
    | 'CREDENTIAL_TOGGLED'
    | 'USER_CREATED'
    | 'USER_DELETED'
    | 'DEVICE_DEACTIVATED'
    | 'ADMIN_LOGIN'
    | 'ADMIN_LOGOUT'
    | 'ADMIN_CREATED'
    | 'ADMIN_UPDATED'
    | 'ADMIN_PASSWORD_CHANGED'
    | 'WEBHOOK_TRIGGERED'
    | 'WEBHOOK_FAILED'
    | 'FILE_UPLOADED'
    | 'CREDENTIAL_VERSION_CREATED'
    | 'CREDENTIAL_TESTED'
    | 'CREDENTIAL_ACTIVATED'
    | 'CREDENTIAL_DEACTIVATED'
    | 'WEBHOOK_CREATED'
    | 'WEBHOOK_UPDATED'
    | 'WEBHOOK_SECRET_ROTATED'
    | 'ORG_CREATED'
    | 'ROLE_CREATED'
    | 'ROLE_UPDATED'
    | 'ROLE_DELETED'
    | 'MEMBER_ADDED'
    | 'MEMBER_UPDATED'
    | 'MEMBER_REMOVED';

export type AuditResource =
    | 'app'
    | 'campaign'
    | 'abtest'
    | 'template'
    | 'notification'
    | 'credential'
    | 'user'
    | 'device'
    | 'admin'
    | 'webhook'
    | 'storage'
    | 'credential_version'
    | 'credential_test_run'
    | 'webhook_endpoint'
    | 'organization'
    | 'role'
    | 'org_member';

export interface AuditLogEntry {
    adminUserId?: string;
    action: AuditAction;
    resource: AuditResource;
    resourceId?: string;
    appId?: string;
    details?: Record<string, any>;
    ipAddress?: string;
    userAgent?: string;
}
