[variables]
NODE_ENV = "production"
NIXPACKS_SPA_CADDY = "true"
NIXPACKS_SPA_OUT_DIR = "dist"

[phases.setup]
nixPkgs = ["nodejs_latest", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]
