export interface RouteSurfaceEntry {
  method: "get" | "post" | "put" | "patch" | "delete";
  path: string;
  summary: string;
  tags: string[];
  security?: Array<Record<string, string[]>>;
}

const bearerOnly = [{ bearerAuth: [] }];

export const mountedRouteSurface: RouteSurfaceEntry[] = [
  // Admin
  {
    method: "post",
    path: "/admin/login",
    summary: "Admin login",
    tags: ["Admin"],
  },
  {
    method: "post",
    path: "/admin/signup",
    summary: "Signup invited admin",
    tags: ["Admin"],
  },
  {
    method: "post",
    path: "/admin/setup",
    summary: "Setup initial admin",
    tags: ["Admin"],
  },
  {
    method: "post",
    path: "/admin/logout",
    summary: "Admin logout",
    tags: ["Admin"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/admin/me",
    summary: "Current admin",
    tags: ["Admin"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/admin/change-password",
    summary: "Change password",
    tags: ["Admin"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/admin/users",
    summary: "Create admin user",
    tags: ["Admin"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/admin/users",
    summary: "List admin users",
    tags: ["Admin"],
    security: bearerOnly,
  },
  {
    method: "patch",
    path: "/admin/users/{id}",
    summary: "Update admin user",
    tags: ["Admin"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/admin/users/assign-app",
    summary: "Assign app manager",
    tags: ["Admin"],
    security: bearerOnly,
  },
  {
    method: "delete",
    path: "/admin/users/{adminUserId}/apps/{appId}",
    summary: "Remove app manager assignment",
    tags: ["Admin"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/admin/users/{id}/apps",
    summary: "Replace admin app assignments",
    tags: ["Admin"],
    security: bearerOnly,
  },

  // Organizations
  {
    method: "post",
    path: "/orgs",
    summary: "Create organization",
    tags: ["Organizations"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/orgs",
    summary: "List organizations",
    tags: ["Organizations"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/orgs/{orgId}/roles",
    summary: "Create role",
    tags: ["Organizations"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/orgs/{orgId}/roles",
    summary: "List roles",
    tags: ["Organizations"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/orgs/{orgId}/roles/{roleId}",
    summary: "Update role",
    tags: ["Organizations"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/orgs/{orgId}/members",
    summary: "Add member",
    tags: ["Organizations"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/orgs/{orgId}/members/{memberId}",
    summary: "Update member",
    tags: ["Organizations"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/orgs/permissions",
    summary: "List permissions",
    tags: ["Organizations"],
    security: bearerOnly,
  },

  // Upload
  {
    method: "post",
    path: "/uploads",
    summary: "Upload file",
    tags: ["Uploads"],
    security: bearerOnly,
  },

  // Stats & Audit
  {
    method: "get",
    path: "/stats/dashboard",
    summary: "Dashboard stats",
    tags: ["Stats"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/stats/apps",
    summary: "App stats",
    tags: ["Stats"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/stats/trend",
    summary: "Notification trend",
    tags: ["Stats"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/stats/providers",
    summary: "Provider stats",
    tags: ["Stats"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/audit",
    summary: "Audit logs",
    tags: ["Audit"],
    security: bearerOnly,
  },

  // Apps
  {
    method: "post",
    path: "/apps",
    summary: "Create app",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/apps",
    summary: "List apps",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/apps/{id}",
    summary: "Get app",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/apps/{id}",
    summary: "Update app",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{id}/kill",
    summary: "Disable app",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{id}/revive",
    summary: "Revive app",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/apps/{id}/webhook",
    summary: "Configure app webhook",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{id}/webhook/test",
    summary: "Test app webhook",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{id}/env",
    summary: "Create app environment",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/apps/{id}/access",
    summary: "List app collaborators and invites",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{id}/invites",
    summary: "Invite app collaborator",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "delete",
    path: "/apps/{id}/invites/{inviteId}",
    summary: "Revoke app invite",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/apps/{appId}/api-keys",
    summary: "List app API keys",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{appId}/api-keys",
    summary: "Create app API key",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{appId}/api-keys/{keyId}/revoke",
    summary: "Revoke app API key",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{appId}/api-keys/{keyId}/rotate",
    summary: "Rotate app API key",
    tags: ["Apps"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/apps/{appId}/env/{env}/credentials",
    summary: "List credentials",
    tags: ["Credentials"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{appId}/env/{env}/credentials/{provider}",
    summary: "Create credential version",
    tags: ["Credentials"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/credentials/{credentialVersionId}/test",
    summary: "Test credential version",
    tags: ["Credentials"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/credentials/{credentialVersionId}/activate",
    summary: "Activate credential version",
    tags: ["Credentials"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/apps/{appId}/env/{env}/webhooks",
    summary: "Configure webhooks",
    tags: ["Webhooks"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{appId}/env/{env}/webhooks/rotate-secret",
    summary: "Rotate webhook secret",
    tags: ["Webhooks"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/apps/{appId}/env/{env}/webhooks/test",
    summary: "Test webhook",
    tags: ["Webhooks"],
    security: bearerOnly,
  },

  // Users / Devices
  { method: "post", path: "/users", summary: "Register user", tags: ["Users"] },
  {
    method: "get",
    path: "/users",
    summary: "List users",
    tags: ["Users"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/users/{id}",
    summary: "Get user",
    tags: ["Users"],
    security: bearerOnly,
  },
  {
    method: "delete",
    path: "/users/{id}",
    summary: "Delete user",
    tags: ["Users"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/users/device",
    summary: "Register device",
    tags: ["Devices"],
  },
  {
    method: "get",
    path: "/devices",
    summary: "List devices",
    tags: ["Devices"],
    security: bearerOnly,
  },
  {
    method: "patch",
    path: "/devices/{id}/deactivate",
    summary: "Deactivate device",
    tags: ["Devices"],
    security: bearerOnly,
  },

  // Notifications / Events / Templates
  {
    method: "post",
    path: "/notifications",
    summary: "Create notification",
    tags: ["Notifications"],
  },
  {
    method: "post",
    path: "/notifications/test",
    summary: "Send test notification",
    tags: ["Notifications"],
  },
  {
    method: "post",
    path: "/notifications/{id}/cancel",
    summary: "Cancel notification",
    tags: ["Notifications"],
  },
  {
    method: "post",
    path: "/notifications/{id}/schedule",
    summary: "Schedule notification",
    tags: ["Notifications"],
  },
  {
    method: "post",
    path: "/notifications/{id}/force-send",
    summary: "Force send notification",
    tags: ["Notifications"],
  },
  {
    method: "post",
    path: "/events/{eventName}",
    summary: "Send event",
    tags: ["Events"],
  },
  {
    method: "post",
    path: "/templates",
    summary: "Create template",
    tags: ["Templates"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/templates",
    summary: "List templates",
    tags: ["Templates"],
  },
  {
    method: "get",
    path: "/templates/{id}",
    summary: "Get template",
    tags: ["Templates"],
  },
  {
    method: "put",
    path: "/templates/{id}",
    summary: "Update template",
    tags: ["Templates"],
    security: bearerOnly,
  },
  {
    method: "delete",
    path: "/templates/{id}",
    summary: "Delete template",
    tags: ["Templates"],
    security: bearerOnly,
  },

  // Automation workflows
  {
    method: "post",
    path: "/automations",
    summary: "Create automation workflow",
    tags: ["Automations"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/automations",
    summary: "List automation workflows",
    tags: ["Automations"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/automations/{id}",
    summary: "Get automation workflow",
    tags: ["Automations"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/automations/{id}",
    summary: "Update automation workflow",
    tags: ["Automations"],
    security: bearerOnly,
  },
  {
    method: "delete",
    path: "/automations/{id}",
    summary: "Delete automation workflow",
    tags: ["Automations"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/automations/{id}/toggle",
    summary: "Toggle automation workflow",
    tags: ["Automations"],
    security: bearerOnly,
  },

  // Automation triggers
  {
    method: "post",
    path: "/automation-triggers",
    summary: "Create automation trigger",
    tags: ["Automation Triggers"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/automation-triggers",
    summary: "List automation triggers",
    tags: ["Automation Triggers"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/automation-triggers/{id}",
    summary: "Get automation trigger",
    tags: ["Automation Triggers"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/automation-triggers/{id}",
    summary: "Update automation trigger",
    tags: ["Automation Triggers"],
    security: bearerOnly,
  },
  {
    method: "delete",
    path: "/automation-triggers/{id}",
    summary: "Delete automation trigger",
    tags: ["Automation Triggers"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/automation-triggers/{id}/test",
    summary: "Test automation trigger",
    tags: ["Automation Triggers"],
    security: bearerOnly,
  },

  // A/B tests
  {
    method: "post",
    path: "/ab-tests",
    summary: "Create AB test",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/ab-tests",
    summary: "List AB tests",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/ab-tests/{id}",
    summary: "Get AB test",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/ab-tests/{id}",
    summary: "Update AB test",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/ab-tests/{id}/draft",
    summary: "Save AB test draft",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/ab-tests/{id}/start",
    summary: "Start AB test",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/ab-tests/{id}/cancel",
    summary: "Cancel AB test",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/ab-tests/{id}/duplicate",
    summary: "Duplicate AB test",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "delete",
    path: "/ab-tests/{id}",
    summary: "Delete AB test",
    tags: ["AB Tests"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/ab-tests/{id}/results",
    summary: "AB test results",
    tags: ["AB Tests"],
    security: bearerOnly,
  },

  // Campaigns
  {
    method: "post",
    path: "/campaigns",
    summary: "Create campaign",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/campaigns",
    summary: "List campaigns",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/audience-estimate",
    summary: "Audience estimate",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/campaigns/{id}",
    summary: "Get campaign",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/campaigns/{id}",
    summary: "Update campaign",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "put",
    path: "/campaigns/{id}/draft",
    summary: "Save campaign draft",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/{id}/schedule",
    summary: "Schedule campaign",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/{id}/send",
    summary: "Send campaign now",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/{id}/cancel",
    summary: "Cancel campaign",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/{id}/duplicate",
    summary: "Duplicate campaign",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "delete",
    path: "/campaigns/{id}",
    summary: "Delete campaign",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/{id}/csv",
    summary: "Upload campaign CSV",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "get",
    path: "/campaigns/{id}/stats",
    summary: "Campaign stats",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/{id}/submit-review",
    summary: "Submit campaign for review",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/{id}/approve",
    summary: "Approve campaign",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/{id}/replay-failures",
    summary: "Replay campaign failures",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
  {
    method: "post",
    path: "/campaigns/estimate",
    summary: "Detailed campaign estimate",
    tags: ["Campaigns"],
    security: bearerOnly,
  },
];
